//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.thrustcurve.org/2009/DownloadRequest")]
[System.Xml.Serialization.XmlRootAttribute("download-request", Namespace="http://www.thrustcurve.org/2009/DownloadRequest", IsNullable=false)]
public partial class downloadrequest {
    
    private object itemField;
    
    private downloadrequestFormat formatField;
    
    private bool formatFieldSpecified;
    
    private downloadrequestLicense licenseField;
    
    private bool licenseFieldSpecified;
    
    private string maxresultsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("motor-id", typeof(string), DataType="integer")]
    [System.Xml.Serialization.XmlElementAttribute("motor-ids", typeof(downloadrequestMotorids))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    public downloadrequestFormat format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool formatSpecified {
        get {
            return this.formatFieldSpecified;
        }
        set {
            this.formatFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public downloadrequestLicense license {
        get {
            return this.licenseField;
        }
        set {
            this.licenseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool licenseSpecified {
        get {
            return this.licenseFieldSpecified;
        }
        set {
            this.licenseFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("max-results", DataType="positiveInteger")]
    public string maxresults {
        get {
            return this.maxresultsField;
        }
        set {
            this.maxresultsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.thrustcurve.org/2009/DownloadRequest")]
public partial class downloadrequestMotorids {
    
    private string[] idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("id", DataType="integer")]
    public string[] id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.thrustcurve.org/2009/DownloadRequest")]
public enum downloadrequestFormat {
    
    /// <remarks/>
    CompuRoc,
    
    /// <remarks/>
    ALT4,
    
    /// <remarks/>
    RASP,
    
    /// <remarks/>
    RockSim,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.thrustcurve.org/2009/DownloadRequest")]
public enum downloadrequestLicense {
    
    /// <remarks/>
    PD,
    
    /// <remarks/>
    free,
    
    /// <remarks/>
    other,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,
}
