//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace RocketClubs.ThrustCurve
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.thrustcurve.org/2009/DownloadResponse")]
    [System.Xml.Serialization.XmlRootAttribute("download-response", Namespace = "http://www.thrustcurve.org/2009/DownloadResponse", IsNullable = false)]
    public partial class downloadresponse
    {

        private downloadresponseResult[] resultsField;

        private string errorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable = false)]
        public downloadresponseResult[] results
        {
            get
            {
                return this.resultsField;
            }
            set
            {
                this.resultsField = value;
            }
        }

        /// <remarks/>
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.thrustcurve.org/2009/DownloadResponse")]
    public partial class downloadresponseResult
    {

        private string motoridField;

        private string simfileidField;

        private downloadresponseResultFormat formatField;

        private downloadresponseResultSource sourceField;

        private downloadresponseResultLicense licenseField;

        private byte[] dataField;

        private string infourlField;

        private string dataurlField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("motor-id", DataType = "integer")]
        public string motorid
        {
            get
            {
                return this.motoridField;
            }
            set
            {
                this.motoridField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("simfile-id", DataType = "integer")]
        public string simfileid
        {
            get
            {
                return this.simfileidField;
            }
            set
            {
                this.simfileidField = value;
            }
        }

        /// <remarks/>
        public downloadresponseResultFormat format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        /// <remarks/>
        public downloadresponseResultSource source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        public downloadresponseResultLicense license
        {
            get
            {
                return this.licenseField;
            }
            set
            {
                this.licenseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("info-url", DataType = "anyURI")]
        public string infourl
        {
            get
            {
                return this.infourlField;
            }
            set
            {
                this.infourlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data-url", DataType = "anyURI")]
        public string dataurl
        {
            get
            {
                return this.dataurlField;
            }
            set
            {
                this.dataurlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.thrustcurve.org/2009/DownloadResponse")]
    public enum downloadresponseResultFormat
    {

        /// <remarks/>
        CompuRoc,

        /// <remarks/>
        ALT4,

        /// <remarks/>
        RASP,

        /// <remarks/>
        RockSim,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.thrustcurve.org/2009/DownloadResponse")]
    public enum downloadresponseResultSource
    {

        /// <remarks/>
        cert,

        /// <remarks/>
        mfr,

        /// <remarks/>
        user,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.thrustcurve.org/2009/DownloadResponse")]
    public enum downloadresponseResultLicense
    {

        /// <remarks/>
        PD,

        /// <remarks/>
        free,

        /// <remarks/>
        other,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }
}