//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace RocketClubs.ThrustCurve
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.1")]
    [System.Serializable()]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.thrustcurve.org/2008/MetadataRequest")]
    [XmlRoot("metadata-request", Namespace = "http://www.thrustcurve.org/2008/MetadataRequest", IsNullable = false)]
    public partial class metadatarequest
    {

        private string manufacturerField;

        private string impulseclassField;

        private decimal diameterField;

        private bool diameterFieldSpecified;

        private metadatarequestType typeField;

        private bool typeFieldSpecified;

        private string certorgField;

        /// <remarks/>
        public string manufacturer
        {
            get
            {
                return this.manufacturerField;
            }
            set
            {
                this.manufacturerField = value;
            }
        }

        /// <remarks/>
        [XmlElement("impulse-class")]
        public string impulseclass
        {
            get
            {
                return this.impulseclassField;
            }
            set
            {
                this.impulseclassField = value;
            }
        }

        /// <remarks/>
        public decimal diameter
        {
            get
            {
                return this.diameterField;
            }
            set
            {
                this.diameterField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool diameterSpecified
        {
            get
            {
                return this.diameterFieldSpecified;
            }
            set
            {
                this.diameterFieldSpecified = value;
            }
        }

        /// <remarks/>
        public metadatarequestType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement("cert-org")]
        public string certorg
        {
            get
            {
                return this.certorgField;
            }
            set
            {
                this.certorgField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.1")]
    [System.Serializable()]
    [XmlType(AnonymousType = true, Namespace = "http://www.thrustcurve.org/2008/MetadataRequest")]
    public enum metadatarequestType
    {

        /// <remarks/>
        SU,

        /// <remarks/>
        reload,

        /// <remarks/>
        hybrid,
    }
}