//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace RocketClubs.ThrustCurve
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.thrustcurve.org/2008/MetadataResponse")]
    [System.Xml.Serialization.XmlRootAttribute("metadata-response", Namespace = "http://www.thrustcurve.org/2008/MetadataResponse", IsNullable = false)]
    public partial class metadataresponse
    {

        private NameAndAbbrev[] manufacturersField;

        private NameAndAbbrev[] certorgsField;

        private string[] typesField;

        private decimal[] diametersField;

        private string[] impulseclassesField;

        private string errorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("manufacturer", IsNullable = false)]
        public NameAndAbbrev[] manufacturers
        {
            get
            {
                return this.manufacturersField;
            }
            set
            {
                this.manufacturersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("cert-orgs")]
        [System.Xml.Serialization.XmlArrayItemAttribute("cert-org", IsNullable = false)]
        public NameAndAbbrev[] certorgs
        {
            get
            {
                return this.certorgsField;
            }
            set
            {
                this.certorgsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("type", IsNullable = false)]
        public string[] types
        {
            get
            {
                return this.typesField;
            }
            set
            {
                this.typesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("diameter", IsNullable = false)]
        public decimal[] diameters
        {
            get
            {
                return this.diametersField;
            }
            set
            {
                this.diametersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("impulse-classes")]
        [System.Xml.Serialization.XmlArrayItemAttribute("impulse-class", IsNullable = false)]
        public string[] impulseclasses
        {
            get
            {
                return this.impulseclassesField;
            }
            set
            {
                this.impulseclassesField = value;
            }
        }

        /// <remarks/>
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.thrustcurve.org/2008/MetadataResponse")]
    public partial class NameAndAbbrev
    {

        private string abbrevField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string abbrev
        {
            get
            {
                return this.abbrevField;
            }
            set
            {
                this.abbrevField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}