//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace RocketClubs.ThrustCurve
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.thrustcurve.org/2008/SearchRequest")]
    [System.Xml.Serialization.XmlRootAttribute("search-request", Namespace = "http://www.thrustcurve.org/2008/SearchRequest", IsNullable = false)]
    public partial class searchrequest
    {

        private string manufacturerField;

        private string designationField;

        private string brandnameField;

        private string commonnameField;

        private string impulseclassField;

        private decimal diameterField;

        private bool diameterFieldSpecified;

        private searchrequestType typeField;

        private bool typeFieldSpecified;

        private string certorgField;

        private bool hasdatafilesField;

        private bool hasdatafilesFieldSpecified;

        private System.DateTime infoupdatedsinceField;

        private bool infoupdatedsinceFieldSpecified;

        private System.DateTime dataupdatedsinceField;

        private bool dataupdatedsinceFieldSpecified;

        private string maxresultsField;

        /// <remarks/>
        public string manufacturer
        {
            get
            {
                return this.manufacturerField;
            }
            set
            {
                this.manufacturerField = value;
            }
        }

        /// <remarks/>
        public string designation
        {
            get
            {
                return this.designationField;
            }
            set
            {
                this.designationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brand-name")]
        public string brandname
        {
            get
            {
                return this.brandnameField;
            }
            set
            {
                this.brandnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("common-name")]
        public string commonname
        {
            get
            {
                return this.commonnameField;
            }
            set
            {
                this.commonnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("impulse-class")]
        public string impulseclass
        {
            get
            {
                return this.impulseclassField;
            }
            set
            {
                this.impulseclassField = value;
            }
        }

        /// <remarks/>
        public decimal diameter
        {
            get
            {
                return this.diameterField;
            }
            set
            {
                this.diameterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diameterSpecified
        {
            get
            {
                return this.diameterFieldSpecified;
            }
            set
            {
                this.diameterFieldSpecified = value;
            }
        }

        /// <remarks/>
        public searchrequestType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cert-org")]
        public string certorg
        {
            get
            {
                return this.certorgField;
            }
            set
            {
                this.certorgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("has-data-files")]
        public bool hasdatafiles
        {
            get
            {
                return this.hasdatafilesField;
            }
            set
            {
                this.hasdatafilesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hasdatafilesSpecified
        {
            get
            {
                return this.hasdatafilesFieldSpecified;
            }
            set
            {
                this.hasdatafilesFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("info-updated-since", DataType = "date")]
        public System.DateTime infoupdatedsince
        {
            get
            {
                return this.infoupdatedsinceField;
            }
            set
            {
                this.infoupdatedsinceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool infoupdatedsinceSpecified
        {
            get
            {
                return this.infoupdatedsinceFieldSpecified;
            }
            set
            {
                this.infoupdatedsinceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data-updated-since", DataType = "date")]
        public System.DateTime dataupdatedsince
        {
            get
            {
                return this.dataupdatedsinceField;
            }
            set
            {
                this.dataupdatedsinceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataupdatedsinceSpecified
        {
            get
            {
                return this.dataupdatedsinceFieldSpecified;
            }
            set
            {
                this.dataupdatedsinceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("max-results", DataType = "positiveInteger")]
        public string maxresults
        {
            get
            {
                return this.maxresultsField;
            }
            set
            {
                this.maxresultsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.thrustcurve.org/2008/SearchRequest")]
    public enum searchrequestType
    {

        /// <remarks/>
        SU,

        /// <remarks/>
        reload,

        /// <remarks/>
        hybrid,
    }
}